### ISSUE TITLE
Convert mentions too!

### ISSUE THREAD

**Issue by MatejMecka** [rTeenDeveloper/Slack-----Discord-Bridge#7]
`[Slack](matejmecka) <@U4CDSUR1R> why do they word...`

Mentions aren't converted too. So I guess we can take inside the <> and check if the 2nd letter is a @ and then look for the username of that person.

**Comment by ghost** [comment]
So we could try to do this, but i foresee a couple major issue...  If someone joins just the slack or just the discord, then their username will not be pingable on the other.  Along hte same line, even if they are registered on both, they might not have the same username.

I would suggest allowing a user to run a command with the slack bot/discord bot, binding the two accounts together, and only applying the username transformation to those that have asked for it.

**Comment by MatejMecka** [comment]
That's a big problem. A very big one which we should fix as soon as we can.  Right now the users can only see that they've been pinged but not receive the notifications which something should be done as soon as possible
